### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by waczny** [phosek/osTicket_task-ticket-count#1]
Hi,
I just tested it and it does not show me anything. I updated the count files and the class.nav

**Comment by phosek** [comment]
The problem on the client side is not showing up for me. However, here is commit dc14004, which conditions the loading (including) of files only if an administrator (staff) is logged in. So the files will not be loaded at all on the client side.

**Comment by waczny** [comment]
Before your fix yes I had the problem on the client side. Now

**Comment by waczny** [comment]
Nevermind, I forgot to also edit back lines 140-141
